### ISSUE TITLE
Getting Error with ruby 1.9.3

### ISSUE THREAD

**Issue by ankpandey** [zaru/webpush#19]
@rossta I tried to send payload on chrome but I am getting below mentioned error:
`NoMethodError: undefined method auth_tag=' for #<OpenSSL::Cipher:0x00000006510d28>
	from .rvm/gems/ruby-1.9.3-p551@test/gems/webpush-0.2.1/lib/webpush/encryption.rb:63:in encrypt_payload'
	from .rvm/gems/ruby-1.9.3-p551@test/gems/webpush-0.2.1/lib/webpush/encryption.rb:33:in encrypt'
	from .rvm/gems/ruby-1.9.3-p551@test/gems/webpush-0.2.1/lib/webpush.rb:42:in build_payload'
	from .rvm/gems/ruby-1.9.3-p551@test/gems/webpush-0.2.1/lib/webpush.rb:32:in payload_send'
	from (irb):2
`
I am using ruby 1.9.3 and I tried to hit `Webpush.payload_send` method via rails console but getting auth tag issue.

**Comment by rossta** [comment]
@ankpandey Sorry to hear that. So far, the gem has only been written to support [ruby `2.3`](https://github.com/zaru/webpush/blob/32b19f33b6dca8f961b4e7cab5d406de7c381852/.travis.yml#L3). 

Since `1.9.3.` and `2.0` have reached "end-of-life", it may be unlikely that support in this gem will be added later for those earlier rubies.

**Comment by zaru** [comment]
@ankpandey Thank you for trying.
but i don't plan to support 1.9. webpush gem i support only Ruby2.1+.
