### ISSUE TITLE
Trigger push notification to multiple endpoint or subscribers in same request 

### ISSUE THREAD

**Issue by subhashsaran** [zaru/webpush#21]
Hey, i was able to send multiple notifications by passing an array of registration ids in single request. it's not ideal to perform so many requests i want to perform multiple notifications

**Comment by zaru** [comment]
Hi @subhashsaran
I also can send multiple messages in a single request is believe that ideal.
However, I think that it can not receive the data of the payload client When you use the registration_ids.
I'm operation to deliver multiple messages by the asynchronous processing using, for example, Sidekiq.

**Comment by subhashsaran** [comment]
Exactly I tried passing multiple registration ids in but it was not parsing
payload data properly. Sending one by one is not that good for us as we
have thousands of subscribers. Can you suggest some other better way ??

**Comment by rhys-vdw** [comment]
Hi, also interested in this functionality.

**Comment by fatal10110** [comment]
up

**Comment by rajatgarg79** [comment]
Hey - did anyone resolve this? We are trying to do batch processing also

**Comment by collimarco** [comment]
The Push API and RFC 8030 don't provide a way to send multiple notifications with one HTTP request.

Based on the current standard, you need to make N requests in order to deliver a notification to N devices. 

This isn't going to change any time soon so I think that this issue should be closed. @zaru

**Comment by jeopard** [comment]
~~hey! FCM implemented batch requests ([link](https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-multiple-devices))~~

**Comment by collimarco** [comment]
@jeopard **That page doesn't seem related to Web Push**, which is the standard supported by all major browsers. It seems related to the **Firebase proprietary API**, which is something completely different. 

Also note that the Firebase API always supported **bulk notifications for apps**, but that feature wasn't available for the web (I don't know now).

**Comment by jeopard** [comment]
You're right. I had slightly misunderstood the internals of the gem. I gave the README another read now, and realised that using the FCM API and adding another service in the middle makes no sense in this gem.

Btw, I was going through the legacy API for FCM, and I noticed that it supports multiple registration IDs, up to 1000. [Here](https://firebase.google.com/docs/cloud-messaging/http-server-ref) are the docs, you can check the `registration_ids` param. I just tried it with 2 sessions in Chrome and Firefox locally, and it worked fine. I assume that it's been around for some time since it's the "legacy" API. The new API also seems to support it, it's shown in the link that I posted above
