### ISSUE TITLE
403 - aud claim in the token MUST include the origin of the push resource URL

### ISSUE THREAD

**Issue by kiddrew** [zaru/webpush#82]
I'm getting this error message randomly. The code looks simple enough, so I don't immediately see what could be causing it. The endpoint param is this format:

`https://android.googleapis.com/gcm/send/eDD5G1tIe9...`

But it doesn't seem to be isolated to android URLs.

**Comment by collimarco** [comment]
We deliver to millions of recipients and I have never seen this error: the problem is definitely related to the endpoint, **not a library bug**.

The domain `android.googleapis.com` belongs to GCM, which was deprecated and then removed many months ago. For Chrome the correct domain is `fcm.googleapis.com`.

**Comment by kiddrew** [comment]
Interesting. I just created that push subscription a few weeks ago, and that's the URL they gave me back. I'll just start catching those and invalidating the subscriptions. Thanks for the help
