### ISSUE TITLE
Is Webpush.payload_send thread-safe?

### ISSUE THREAD

**Issue by Inversion-des** [zaru/webpush#90]
Or the more broad question is: 
what is a proper way to send a push notification to many users efficiently?

**Comment by SampsonCrowley** [comment]
Not a maintainer, but that seems like something that should only be done inside of a background worker regardless

**Comment by collimarco** [comment]
@Inversion-des We use this library at scale for Pushpad (thousands of notifications / second) and it works perfectly. You need to use [Sidekiq](https://github.com/mperham/sidekiq) to **create a background job for each single delivery** (note that Web Push itself doesn't support batch notifications to multiple recipients).

Since Sidekiq uses threads and we have never had problems the answer is _Yes_.

Also you can see from code that a new instance is created each time you call that method:
https://github.com/zaru/webpush/blob/master/lib/webpush.rb#L38

So **it is thread-safe**.
